# Generated by Django 4.2.13 on 2024-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0001_initial"),
    ]

    operations = []
