# Generated by Django 4.2.13 on 2024-06-28 09:08

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0002_trigram"),
    ]

    operations = [
        UnaccentExtension()
    ]
