# Generated by Django 5.1.2 on 2024-10-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0003_unaccent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionperson_profession_father',
            name='parentprofession',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profession_mother',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profession_father',
        ),
        migrations.RemoveField(
            model_name='versionperson_profession_mother',
            name='parentprofession',
        ),
        migrations.RemoveField(
            model_name='versionperson_profession_father',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versionperson_profession_father',
            name='person',
        ),
        migrations.RemoveField(
            model_name='versionperson_profession_mother',
            name='history',
        ),
        migrations.RemoveField(
            model_name='versionperson_profession_mother',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='versionevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Event', 'verbose_name_plural': 'historical Events'},
        ),
        migrations.AlterModelOptions(
            name='versioninstitution',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Institution', 'verbose_name_plural': 'historical Institutions'},
        ),
        migrations.AlterModelOptions(
            name='versionperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Person', 'verbose_name_plural': 'historical Persons'},
        ),
        migrations.AlterModelOptions(
            name='versionplace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Place', 'verbose_name_plural': 'historical Places'},
        ),
        migrations.AlterModelOptions(
            name='versionwork',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Work', 'verbose_name_plural': 'historical Works'},
        ),
        migrations.DeleteModel(
            name='Parentprofession',
        ),
        migrations.DeleteModel(
            name='VersionPerson_profession_father',
        ),
        migrations.DeleteModel(
            name='VersionPerson_profession_mother',
        ),
    ]
